[web_servers]
server1 ansible_host=192.168.56.102 ansible_user=christian target_user=christian
CentOS ansible_host=192.168.56.120 ansible_user=christian target_user=christian
[db_servers]
CentOS ansible_host=192.168.56.120 ansible_user=christian target_user=christian
server2 ansible_host=192.168.56.121 ansible_user=christian target_user=christian
[file_servers]
server3 ansible_host=192.168.56.119 ansible_user=christian target_user=christian
[workstations]
workstation ansible_host=192.168.56.101 ansible_user=christian target_user=christian
